version: '3'
services:
  # localstack
  localstack:
    image: localstack/localstack:0.12.14
    container_name: localstack
    ports:
      - '4566:4566'
    environment:
      - DEFAULT_REGION=ap-northeast-1
      - SERVICES=dynamodb
