GET http://localhost:8080/users/health

GET http://localhost:8080/users/pool/test001@dxc.com

GET http://localhost:8080/users/pool/test002@dxc.com

GET http://localhost:8080/users/pool/test003@dxc.com


POST http://localhost:8080/users/
content-type: application/json

{
  "userId" : "test004@dxc.com",
  "userName": "test004",
  "email": "test004@dxc.com"
}

POST http://localhost:8080/users/admin
content-type: application/json

{
  "userId" : "test005@dxc.com",
  "userName": "test005",
  "email": "test005@dxc.com"
}

GET http://localhost:8080/users/admins
