// API DOMAIN

export const VERSION = `${process.env.VERSION}`;

export const Authority = {
  ADMIN: 'TENANT_ADMIN',
  PARENT: 'PARENT',
  STUDENT: 'STUDENT',
};

export const SUBJECT = {
  LANGUAGE: '1',
  SCIENCE: '2',
  SOCIETY: '3',
  ENGLISH: '0',
  ABILITY_LANGUAGE: '101',
  ABILITY_SCIENCE: '102',
  ABILITY_SOCIETY: '103',
  ABILITY_ENGLISH: '100',
};

export const SUBJECT_NORMAL = [SUBJECT.ENGLISH, SUBJECT.LANGUAGE, SUBJECT.SCIENCE, SUBJECT.SOCIETY];
export const SUBJECT_ABILITY = [
  SUBJECT.ABILITY_ENGLISH,
  SUBJECT.ABILITY_LANGUAGE,
  SUBJECT.ABILITY_SCIENCE,
  SUBJECT.ABILITY_SOCIETY,
];

export enum SIGN_STATUS {
  NOT_LOGIN,
  NEW_PASSWORD_REQUIRED,
  MFA_REQUIRED,
  LOGINED,
}

export enum EDIT_MODE {
  REGIST,
  EDIT,
  READONLY,
}
