version: '3'
services:
  # localstack
  localstack:
    image: user_manager:latest
    container_name: user_manager
    ports:
      - '9000:8080'
    environment:
      - AWS_REGION=ap-northeast-1
      - TABLE_NAME_SETTINGS=pkc-settings-376965
      - TABLE_NAME_USERS=pkc-users-376965
