export * as CurriculumService from './curriculums';
export * as GroupService from './groups';
export * as QuestionService from './questions';
export * as ReportService from './reports';
export * as LearningService from './leaning';
export * as AbilityService from './ability';
export * as UserService from './users';
export * as WordService from './words';
export * as TraceService from './traces';
