GET http://localhost:8080/v1/auth/health


POST http://localhost:8080/v1/auth/login
Content-Type: application/json

{
  "username": "wwalpha80@gmail.com",
  "password": "NsNx$jP1",
  "newPassword": "AAAAAAAAAAA"
}

POST http://localhost:8080/auth
Content-Type: application/json

{
  "username": "ktou@dxc.com",
  "password": "Session10+"
}