# Uncomment the next line to define a global platform for your project
platform :ios, '16.2'

target 'PocketCards' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PocketCards
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'AmplifyPlugins/AWSS3StoragePlugin'
  pod 'Alamofire'
  pod 'Charts', '= 4.1.0'
  pod 'Kingfisher', '~> 7.0'
  pod 'SwiftFormat/CLI'
end

target 'PocketCards2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PocketCards
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'AmplifyPlugins/AWSS3StoragePlugin'
  pod 'Alamofire'
  pod 'Charts', '= 4.1.0'
  pod 'Kingfisher', '~> 7.0'
  pod 'SwiftFormat/CLI'
end