# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'PocketCards' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PocketCards
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'Alamofire'
  pod 'Charts'
  pod 'Kingfisher', '~> 7.0'
  pod 'SwiftFormat/CLI'
end
