region="ap-northeast-1"
translation_api_key="XXXXXXXXXXXXXXXXXX"
ipa_api_key="XXXXXXXXXXXXXXXXXX"
dns_name_servers="test111111111"
identity_provider_id="XXXXXXXXXXXXXXXXXX"
identity_provider_secret="XXXXXXXXXXXXXXXXXX"