domain_name          = "onecloudlabo.com"
google_client_id     = "XXXXXXXXXXXXXXXXXX"
google_client_secret = "XXXXXXXXXXXXXXXXXX"
api_key_translation  = "XXXXXXXXXXXXXXXXXX"
api_key_ipa          = "XXXXXXXXXXXXXXXXXX"
