domain_name              = "onecloudlabo.com"
identity_provider_id     = "XXXXXXXXXXXXXXXXXX"
identity_provider_secret = "XXXXXXXXXXXXXXXXXX"
api_key_translation      = "XXXXXXXXXXXXXXXXXX"
api_key_ipa              = "XXXXXXXXXXXXXXXXXX"
