name: PUSH_B) Users Manager Build

on:
  push:
    paths:
      - backend/nodejs/user_manager/**
      - backend/nodejs/typings/**
      - .github/workflows/push_backend_users.yml
      - .github/workflows/reuse_build_ci.yml
    branches-ignore:
      - releases/**
      - master

jobs:
  UserManager:
    uses: ./.github/workflows/reuse_build_ci.yml
    with:
      working-directory: backend/nodejs/user_manager
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
