name: PUSH_T) Terraform Plan

on:
  push:
    branches-ignore:
      - releases/**
    paths:
      - 'infrastructure/terraform/**'
      - 'backend/terraform/**'
      - '.github/workflows/**'

permissions:
  contents: read
  id-token: write

jobs:
  Terraform_Setup:
    uses: ./.github/workflows/reuse_terraform.yml
    with:
      environment: dev
      working-directory: infrastructure/terraform/setup
      apply: true
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_VARS: ${{ secrets.TERRAFORM_VARS }}

  Terraform_Service:
    needs: Terraform_Setup
    uses: ./.github/workflows/reuse_terraform.yml
    with:
      environment: dev
      working-directory: infrastructure/terraform/services
      apply: true
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_VARS: ${{ secrets.TERRAFORM_VARS }}

  Terraform_Backend:
    needs: Terraform_Service
    uses: ./.github/workflows/reuse_terraform.yml
    with:
      environment: dev
      working-directory: backend/terraform
      apply: true
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_VARS: ${{ secrets.TERRAFORM_VARS }}
