name: PUSH_F) Users React Build

on:
  push:
    paths:
      - frontend/react/**
      - .github/workflows/push_frontend_users.yml
      - .github/workflows/reuse_react.yml
    branches-ignore:
      - releases/**
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: ap-northeast-1
  TF_WORKSPACE: dev
  WORKING_DIR: frontend/react/users
  NODE_ENV: production
  SSM_PARAMETER_NAME: /pkc/frontend/users

jobs:
  Users:
    uses: ./.github/workflows/reuse_react.yml
    with:
      environment: dev
      region: ap-northeast-1
      working-directory: frontend/react
      module: users
      deploy: false
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
