name: PUSH_T) Backend Build

on:
  workflow_run:
    workflows:
      - PUSH_T) Service Build
      - PUSH_B) Batch Build
    branches:
      - master
    types:
      - completed

env:
  AWS_REGION: ap-northeast-1
  WORKING_DIR: backend/terraform
  ENVIRONMENT: dev

jobs:
  Terraform:
    uses: ./.github/workflows/reuse_terraform.yml
    with:
      region: ${{ env.AWS_REGION }}
      working-directory: ${{ env.WORKING_DIR }}
      environment: ${{ env.ENVIRONMENT }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_VARS: ${{ secrets.TERRAFORM_VARS }}
