name: PUSH_T) Setup Build

on:
  push:
    paths:
      - infrastructure/terraform/setup/**
      - infrastructure/terraform/services/**
      - backend/terraform/**
      - .github/workflows/push_terraform_setup.yml
      - .github/workflows/push_terraform_services.yml
      - .github/workflows/push_terraform_backend.yml
      - .github/workflows/reuse_terraform.yml
    branches-ignore:
      - releases/**
  workflow_run:
    workflows:
      - PUSH_B) Lambda Build
      - PUSH_B) Batch Build
    branches:
      - master
    types:
      - completed

env:
  AWS_REGION: ap-northeast-1

jobs:
  Setup:
    uses: ./.github/workflows/reuse_terraform.yml
    with:
      region: ${{ env.AWS_REGION }}
      working-directory: infrastructure/terraform/setup
      environment: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_VARS: ${{ secrets.TERRAFORM_VARS }}

  Service:
    needs:
      - Setup
    uses: ./.github/workflows/reuse_terraform.yml
    with:
      region: ap-northeast-1
      working-directory: infrastructure/terraform/services
      environment: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_VARS: ${{ secrets.TERRAFORM_VARS }}

  Backend:
    needs:
      - Service
    uses: ./.github/workflows/reuse_terraform.yml
    with:
      region: ap-northeast-1
      working-directory: backend/terraform
      environment: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_VARS: ${{ secrets.TERRAFORM_VARS }}
