name: PUSH_B) Users Manager Build

on:
  push:
    paths:
      - backend/nodejs/user_manager/**
      - backend/nodejs/typings/**
      - .github/workflows/push_backend_users.yml
      - .github/workflows/reuse_ecs_all.yml
    branches-ignore:
      - releases/**
      - master

jobs:
  Build:
    uses: ./.github/workflows/reuse_build_ci.yml
    with:
      working-directory: backend/nodejs/user_manager
