name: PUSH_B) auth_manager CI

on:
  push:
    branches-ignore:
      - releases/**
    paths:
      - 'backend/nodejs/auth_manager/**'
      - 'backend/nodejs/*'
      - 'backend/nodejs/typings/**'
      - 'package.json'
      - 'yarn.lock'
      - '.nvmrc'
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  AuthManager:
    uses: ./.github/workflows/reuse_build_ci.yml
    with:
      working-directory: backend/nodejs/auth_manager
