name: PUSH_B) Auth Manager Build

on:
  push:
    paths:
      - backend/nodejs/auth_manager/**
      - backend/nodejs/typings/**
      - .github/workflows/push_backend_auth.yml
      - .github/workflows/reuse_build_ci_cd.yml
    branches-ignore:
      - releases/**
      - master

jobs:
  AuthManager:
    uses: ./.github/workflows/reuse_build_ci_cd.yml
    with:
      working-directory: backend/nodejs/auth_manager
      environment: dev
      region: ap-northeast-1
      ECR_REPOSITORY: pkc/backend
      ECS_SERVICE_NAME: pkc-backend
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
