name: PUSH_T) Backend Build

on:
  workflow_run:
    workflows:
      - PUSH_T) Service Build
    branches:
      - master
    types:
      - completed

jobs:
  Terraform:
    uses: ./.github/workflows/reuse_terraform.yml
    with:
      region: ap-northeast-1
      working-directory: backend/terraform
      environment: env
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_VARS: ${{ secrets.TERRAFORM_VARS }}
