name: PUSH_B) Users Manager Build

on:
  push:
    paths:
      - backend/nodejs/user_manager/**
      - backend/nodejs/typings/**
      - .github/workflows/push_backend_users.yml
    branches-ignore:
      - releases/**

jobs:
  Build:
    uses: ./.github/workflows/reuse_ecs_build.yml
    with:
      region: ap-northeast-1
      working-directory: backend/nodejs/user_manager
      environment: dev
      ECS_SERVICE_NAME: user_manager
      ECR_REPOSITORY: pkc/users
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Deploy:
    uses: ./.github/workflows/reuse_ecs_deploy.yml
    needs:
      - Build
    with:
      region: ap-northeast-1
      working-directory: backend/nodejs/user_manager
      environment: dev
      ECS_SERVICE_NAME: user_manager
      ECS_TASK_DEF: pkc-users
      ECS_WAIT_FOR_STABILITY: false
      ECR_IMAGE: ${{ needs.Build.outputs.image }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
