name: PUSH_T) Backend Build

on:
  workflow_run:
    workflows:
      - PUSH_T) Service Build
      - PUSH_B) Batch Build
    branches:
      - master
    types:
      - completed

env:
  AWS_DEFAULT_REGION: ap-northeast-1
  WORKING_DIR: backend/terraform
  TF_WORKSPACE: dev
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

jobs:
  Terraform:
    runs-on: ubuntu-latest
    environment:
      name: dev
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      # source checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI 
      # and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}

      # Backend init
      - name: Terraform Backend
        run: |
          terraform init
          terraform plan -out=backend
          terraform apply "backend"
