name: COM) Build CI

on:
  workflow_call:
    # inputs
    inputs:
      environment:
        required: false
        type: string
        default: dev
      region:
        required: false
        type: string
        default: ap-northeast-1
      working-directory:
        required: true
        type: string
    # secrets
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  BUILD:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      AWS_DEFAULT_REGION: ${{ inputs.region }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      # source checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 14.x

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      # Install and Build
      - name: Build
        run: |
          yarn install
          yarn build

      # Unit Test
      - name: Unit Test
        run: |
          docker-compose up -d --build
          sleep 10
          yarn test
          docker-compose down

      # docker build
      - name: Docker Image Build
        run: |
          docker build .
