name: COM) Build CI

on:
  workflow_call:
    # inputs
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  BUILD:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: DUMMY
      AWS_SECRET_ACCESS_KEY: DUMMY
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      # source checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      # Install and Build
      - name: Build
        run: |
          yarn install
          yarn build

      # Unit Test
      - name: Unit Test
        run: |
          docker-compose up -d --build
          sleep 10
          yarn test
          docker-compose down

      # docker build
      - name: Docker Image Build
        run: |
          docker build .
